/*
 * EDITABLE CONTENT: Add, remove, or update entries in these arrays.
 * The page markup is rendered automatically by main.js.
 */
const portfolioData = {
  experience: [
    { organization: "Zionike", context: "Remote - USA", period: "2025 - 2026", role: "IT Customer Support", responsibilities: ["Handled customer support tickets through chat and email.", "Worked using Ivanti and Azure DevOps to track, resolve & escalate technical issues.", "Maintained CRM records and performed data quality checks.", "Updated website content in Drupal."] },
    { organization: "Industrial Training Fund (ITF)", context: "Maitama, Abuja", period: "April, 2025 - July, 2025", role: "Networking Intern", responsibilities: ["Set up and maintained network equipment and hardware.", "Troubleshot connectivity issues across workstations.", "Documented network configurations."] },
    { organization: "Rural Broadband Initiative (RUBI)", context: "Government Day Secondary School, Bwari", period: "2022", role: "IT Operator", responsibilities: ["Managed student databases.", "Introduced students to basic programming concepts during lessons."] },
  ],
  education: [
    { school: "Michael Okpara University of Agriculture, Umudike, Abia State", qualification: "Bachelor of Science, Computer Science", period: "2022 - 2026" }
  ],
  codingProjects: [
    { image: "assets/projecthub.png", title: "ProjectHub", pitch: "A client-facing project intake and fulfillment platform.", tags: ["React", "Supabase", "JAMstack", "Edge Functions"], description: "Originally a Python/Render backend, ProjectHub became a JAMstack rebuild to solve deployment spin-down issues and a broken upload feature. It uses Supabase for database, auth, and storage, with Resend email delivered through Edge Functions.", linkLabel: "View Project", linkUrl: "https://projecthub-qnpp.onrender.com/" },
    { image: "assets/project-placeholder.svg", title: "Impact Global Network (IGN)", pitch: "A discovery site for scholarships, jobs, and grants.", tags: ["Vanilla JS", "JSON", "Static Site"], description: "Built in vanilla HTML, CSS, and JavaScript with a local JSON data layer and localStorage-based auth stubs for a lightweight, approachable experience.", linkLabel: "View Project", linkUrl: "[GITHUB_LINK]" },
    { image: "assets/solar.png", title: "Solar Equipment Catalogue", pitch: "A product catalogue with a direct WhatsApp inquiry flow.", tags: ["HTML/CSS/JS", "JSON", "Client Work"], description: "Client work for David Solex: a static product catalogue with a WhatsApp-based contact flow and a JSON data layer designed to be swapped for a real backend later.", linkLabel: "View Project", linkUrl: "https://davidsolex.netlify.app/" },
    { image: "assets/project-placeholder.svg", title: "SLK Bot", pitch: "Algorithmic trading alerts across multiple markets.", tags: ["Python", "Trading Systems", "REST APIs"], description: "A Python alert bot using Smart Money Concepts methodology across forex, gold, indices, and BTC. It pulls live data through OANDA and Binance REST APIs.", linkLabel: "View Project", linkUrl: "[GITHUB_LINK]" },
    { image: "assets/project-placeholder.svg", title: "Network Intrusion Detection System (NIDS)", pitch: "Live packet analysis with threshold-based anomaly detection.", tags: ["Python", "Scapy", "Network Security", "MITRE ATT&CK"], description: "A final-year seminar and implementation project made from seven Python modules. Scapy handles live packet capture, while Nmap-simulated attack testing validates detections against a MITRE ATT&CK-grounded theoretical base.", linkLabel: "View Project", linkUrl: "[GITHUB_LINK]" }
  ],
  dataAnalysis: [
    { images: ["assets/sales_trend.png", "assets/superstoreimage.png"], title: "Superstore Sales & Profit Analysis", pitch: "A retail performance review across sales, profit, and product categories.", tags: ["Python", "Pandas", "Excel", "Data Visualization"], description: "The issue was straightforward: sales looked healthy on paper, but the business was quietly losing profit in a few product categories. A deeper look at the Superstore data showed that Office Supplies created strong order volume while compressing margins through heavy discounting. At the same time, Technology products were delivering the strongest return per sale and offered the clearest opportunity for growth. The challenge was not a lack of demand, but a mismatch between what was selling and what was actually generating value. The analysis tracked monthly sales trends, compared category-level profit performance, and highlighted the areas where pressure was eroding margins. The response was simple but practical: tighten discounting on lower-margin products and shift more marketing attention toward higher-value technology offerings. If the business keeps volume in the low-margin categories without correcting the structure, profit will continue to shrink even while revenue looks strong. The recommended action is to protect margin first, then grow selectively in the segments with the best return. That balance helps the business stay profitable without slowing momentum.", datasetUrl: "./Data Analysis/Superstore.xlsx" },
    { images: ["assets/dcrimsons_ventures_sales_trend.png", "assets/dcrimsons-image.png"], title: "D'Crimsons Ventures Analysis", pitch: "A compact sales and margin review for a retail venture dataset.", tags: ["Excel", "Analysis", "Retail", "Profitability"], description: "This review focused on a practical question: where was the venture generating value, and where was it quietly losing momentum? The workbook showed that a few products were driving sales volume while weaker margins were reducing overall profit quality. The analysis tracked monthly sales performance, compared profitability by product line, and pinpointed the places where attention needed to shift. The action was to protect margin by reducing discount pressure on weaker lines and increasing focus on the products that delivered the highest return. The message is simple: growth is only useful if the profit behind it is sustainable. This gives the venture a clearer path to improve margin without losing sales momentum.", datasetUrl: "./Data Analysis/D'Crimsons_Ventures.xlsx" }
  ],
  certifications: [
    { title: "Excel Basics for Data Analysis - Coursera", link: "https://www.coursera.org/verify/JCQUF1IYOXFG" },
    { title: "Data Analysis Internship - Bliss Analytics", link: "https://drive.google.com/file/d/12fEw_6btv_ALLgkf_ZOu36ikZnD0eSJP/view?usp=drivesdk" },
    { title: "Junior Cybersecurity Analyst Career Path - CISCO", link: "https://www.credly.com/badges/a95d8d60-c4d9-4972-b936-44e2d59467be/public_url" },
    { title: "Certificate in Customer Experience Management - MTF Institute", link: "https://www.udemy.com/certificate/UC-db5cca59-b434-47bd-9e65-d76407b8aa76/" }
  ],
  socials: { github: "https://github.com/Debright00/Portfolio", linkedin: "https://www.linkedin.com/in/anyanwu-divine-a10930367/", twitter: "https://twitter.com/@robinhood0r" }
};
